a. Импортируйте библиотеку NumPy

In [4]:
import numpy as np

b. Создайте массив из 10 нулей

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

c. Создать массив из 10 единиц

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

d. Создать массив из 10 пятерок

In [ ]:
np.array([5]*10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

e. Создать массив из целых чисел от 10 до 50

In [ ]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

f. Создать массив из четных чисел от 10 до 50

In [ ]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

g. Создать матрицу 3х3 с числами от 0 до 8

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

h. Создать единичную матрицу 3x3

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

i. Используйте NumPy для генерации случайного числа от 0 до 1

In [ ]:
np.random.rand()

0.2997877446171938

j. Используйте NumPy для генерации массива из 25 случайных чисел, взятых из стандартного нормального распределения

In [ ]:
np.random.randn(25)

array([ 1.11426475,  0.44207969, -0.62129402, -0.4650963 , -0.36844244,
        0.99011975, -0.55635757,  0.10468902, -1.03739098, -1.01671271,
       -0.36950837,  0.89678589, -0.76140975, -1.48398791,  1.07321603,
        0.0237089 , -0.83319733, -0.59551967,  0.09243693, -0.45647855,
       -0.4839504 ,  0.22522058,  1.49735066,  0.75411112,  0.56517449])

k. Создайте следующую матрицу используя функции библиотеки NumPy:

In [ ]:
np.arange(0.01, 1.01, 0.01).reshape(10,-1)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

l. Дана стартовая матрица (обязательно запустите код ниже в вашем решении!).
Эта матрица будет использоваться в последующих задачах

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Необходимо написать код который вернет следующую матрицу
из стартовой:

In [ ]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

m. Написать код обращения к элементу который вернет значение 20 из
стартовой матрицы задачи l.

In [ ]:
mat[3, 4]

20

n. Написать код к стартовой матрице задачи l, который воспроизводит
вывод, показанный ниже

In [ ]:
mat[:3, 1].reshape(-1,1)

array([[ 2],
       [ 7],
       [12]])

o. Написать код к стартовой матрице задачи l , который воспроизводит
вывод, показанный ниже

In [ ]:
mat[4]

array([21, 22, 23, 24, 25])

p. Написать код к стартовой матрице задачи l , который воспроизводит
вывод, показанный ниже

In [ ]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

q. Получить сумму всех значений в стартовой матрице mat

In [ ]:
mat.sum()

325

r. Получить стандартное отклонение в стартовой матрице mat

In [ ]:
mat.std()

7.211102550927978

s. Получить сумму значений в колонках в стартовой матрице mat

In [ ]:
print(*mat.sum(0))

55 60 65 70 75
